// Mail tools
export {
    MailTools,
    createMailTools,
    ListAccountsInput,
    ListFoldersInput,
    ListFoldersWithAccountInput,
    ListEmailsInput,
    SearchEmailsInput,
    GetEmailInput,
    GetUnreadCountInput,
    ListAttachmentsInput,
    DownloadAttachmentInput,
    SendEmailInput,
    type ListFoldersParams,
    type ListFoldersWithAccountParams,
    type ListEmailsParams,
    type SearchEmailsParams,
    type GetEmailParams,
    type GetUnreadCountParams,
    type ListAttachmentsParams,
    type DownloadAttachmentParams,
    type SendEmailParams,
    type IContentReader,
    nullContentReader,
} from './mail.js';

// Calendar tools
export {
    CalendarTools,
    createCalendarTools,
    ListCalendarsInput,
    ListEventsInput,
    GetEventInput,
    SearchEventsInput,
    CreateEventInput,
    RespondToEventInput,
    DeleteEventInput,
    UpdateEventInput,
    type ListCalendarsParams,
    type ListEventsParams,
    type GetEventParams,
    type SearchEventsParams,
    type CreateEventParams,
    type CreateEventResult,
    type RecurrenceParams,
    type RespondToEventParams,
    type DeleteEventParams,
    type UpdateEventParams,
    type IEventContentReader,
    type EventDetails,
    nullEventContentReader,
} from './calendar.js';

// Contacts tools
export {
    ContactsTools,
    createContactsTools,
    ListContactsInput,
    SearchContactsInput,
    GetContactInput,
    type ListContactsParams,
    type SearchContactsParams,
    type GetContactParams,
    type IContactContentReader,
    type ContactDetails,
    nullContactContentReader,
} from './contacts.js';

// Tasks tools
export {
    TasksTools,
    createTasksTools,
    ListTasksInput,
    SearchTasksInput,
    GetTaskInput,
    type ListTasksParams,
    type SearchTasksParams,
    type GetTaskParams,
    type ITaskContentReader,
    type TaskDetails,
    nullTaskContentReader,
} from './tasks.js';

// Notes tools
export {
    NotesTools,
    createNotesTools,
    ListNotesInput,
    GetNoteInput,
    SearchNotesInput,
    type ListNotesParams,
    type GetNoteParams,
    type SearchNotesParams,
    type INoteContentReader,
    type NoteDetails,
    nullNoteContentReader,
} from './notes.js';

// Mailbox organization tools
export {
    MailboxOrganizationTools,
    createMailboxOrganizationTools,
    PrepareDeleteEmailInput,
    ConfirmDeleteEmailInput,
    PrepareMoveEmailInput,
    ConfirmMoveEmailInput,
    PrepareArchiveEmailInput,
    ConfirmArchiveEmailInput,
    PrepareJunkEmailInput,
    ConfirmJunkEmailInput,
    PrepareDeleteFolderInput,
    ConfirmDeleteFolderInput,
    PrepareEmptyFolderInput,
    ConfirmEmptyFolderInput,
    PrepareBatchDeleteEmailsInput,
    PrepareBatchMoveEmailsInput,
    ConfirmBatchOperationInput,
    MarkEmailReadInput,
    MarkEmailUnreadInput,
    SetEmailFlagInput,
    ClearEmailFlagInput,
    SetEmailCategoriesInput,
    CreateFolderInput,
    RenameFolderInput,
    MoveFolderInput,
} from './mailbox-organization.js';
